---
- name: Install docker, maven, git, clone repo
  hosts: build
  become: true
  
  tasks:
 
  - name: Ensure git package is present
    apt:
     name: git
     state: present
     update_cache: yes

  # - name: cleaning previous repo clones
  #   shell: rm  -rf /src/build/myboxfuse
  - name: Recursively remove directory
    ansible.builtin.file:
      path: /src/build/
      state: absent  

  - name: Clone a repo from github
    git:
      repo: https://github.com/tovmayor/myboxfuse.git
      dest: /src/build/myboxfuse
      
  - name: Ensure maven package is present
    apt:
     name: maven
     state: present
        
  - name: Ensure docker package is present
    apt:
     name: docker.io
     state: present


- name: prod host actions
  hosts: prod
  become: true

  tasks:
 
  - name: Install docker.io
    apt:
     name: docker.io
     state: present
     update_cache: yes

